# -*- coding: utf-8 -*-
"""스마트폰 사용 시간과 시험 점수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18bJTOmuUi2p6fxs2X4lpnY3CjC3TF4zm
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.array([1, 3, 5])
y = np.array([88, 60, 55])

plt.figure(figsize=(5, 5))
plt.plot(x, y, 'bo')

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x.reshape(-1, 1), y)

plt.plot(x, y, "bo--")
plt.plot(x, model.predict(x.reshape(-1, 1)), "r")

pre_x = int(input("스마트폰 사용시간: "))
y_hat = model.predict([[pre_x]])
print(pre_x, [pre_x], [[pre_x]])
print(f"{pre_x}시간 사용해서 {y_hat}점 예상해요")

year = np.array(range(2000, 2020))
year