# -*- coding: utf-8 -*-
"""짜장면 가격 예측

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G6Ad578P1FhViXsNdanieAg8043gG-fe
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.array([1, 3, 5])
y = np.array([88, 60, 55])

plt.figure(figsize=(5, 5))
plt.plot(x, y, 'bo')

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x.reshape(-1, 1), y)

plt.plot(x, y, "bo--")
plt.plot(x, model.predict(x.reshape(-1, 1)), "r")

pre_x = int(input("스마트폰 사용시간: "))
y_hat = model.predict([[pre_x]])
print(pre_x, [pre_x], [[pre_x]])
print(f"{pre_x}시간 사용해서 {y_hat}점 예상해요")

year = np.array(range(2000, 2020))
year

price = np.array([58.530, 59.262, 62.758, 69.324, 70.953, 71.252, 72.190, 74.886, 84.681, 86.165, 87.240, 93.339,94.445,96.090,97.308,100.00,102.81,106.1,110.83,115.04])
price

price = price / 100 * 4468
price

x = year
y = price
model = LinearRegression()
model.fit(x.reshape(-1, 1), y)

# 편향: bias
model.intercept_

# 기울기: coefficient
model.coef_

plt.figure(figsize=(7, 5))
plt.title("price index")
plt.plot(year, price, "bo--")
plt.plot(x, model.predict(x.reshape(-1, 1)))
plt.xticks(np.arange(1998, 2021, 2))
plt.show()

y = model.predict([[2026]])
y

x = int(input("궁금한 년도의 짜장면 가격"))
y = model.predict([[x]])
print(f"{x}년의 예상된 짜장면 가격은 {y}원")